# Point statistics

The `point statistics` module provides metrics to compare the mean spatial distribution of transcripts in relation to the centroid and the segmented outline of the cell.

In [75]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

#### Run the two metrics one at a time

In [67]:
import spatialdata as sd

import segtraq

sdata = sd.read_zarr("/g/huber/users/lazic/src/SegTraQ/tests/data/xenium_sdata.zarr")

st = segtraq.SegTraQ(sdata, labels_to_cell_id_key="label_id")

/tmp/ipykernel_424963/1558472127.py:4: UserWarning: SpatialData is not stored in the most current format. If you want to use Zarr v3, please write the store to a new location using `sdata.write()`.
  sdata = sd.read_zarr("/g/huber/users/lazic/src/SegTraQ/tests/data/xenium_sdata.zarr")
no parent found for <ome_zarr.reader.Label object at 0x7ffe243ac9e0>: None
no parent found for <ome_zarr.reader.Label object at 0x7ffe243af170>: None

In [68]:
st.ps.centroid_mean_coord_diff("ERBB2")

/home/lazic/.local/share/uv/python/cpython-3.12.11-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

,cell_id,centroid_x,x,centroid_y,y,distance,cell_area,distance_ERBB2
0,bfdoenpl-1,419.906153,419.489258,401.019710,402.799805,25.174418,224.832977,0.111969
1,bfdoompa-1,402.742612,401.793945,424.439958,422.398773,29.986774,264.344697,0.113438
2,bfdoopdk-1,409.078631,412.884583,442.003655,441.477936,43.561857,216.569383,0.201145
3,bfdpabnk-1,415.401363,416.348633,419.043976,412.010742,4.331418,232.645008,0.018618
4,bfdpidpb-1,422.114981,418.583008,290.465105,288.432617,185.162554,168.071569,1.101689
...,...,...,...,...,...,...,...,...
193,nfnmmjmp-1,399.431907,399.127289,286.310040,287.419586,158.979532,332.214543,0.478545
194,nfnmnkml-1,401.742914,404.918945,245.932706,246.018555,222.545951,105.846254,2.102540
195,nfnnbngg-1,449.838115,445.262695,241.616061,243.549805,289.873798,108.826566,2.663631
196,nfnnffgc-1,446.840601,452.239258,255.866030,260.127930,270.968755,228.129383,1.187785
197,nfnnkbag-1,442.209416,448.622070,233.707450,234.924805,298.588687,80.107190,3.727364

In [69]:
sdata["table"].obs[sdata["table"].obs["distance_ERBB2"].notna()]

,cell_id,x_centroid,y_centroid,transcript_counts,control_probe_counts,genomic_control_counts,control_codeword_counts,unassigned_codeword_counts,deprecated_codeword_counts,total_counts,cell_area,nucleus_area,nucleus_count,segmentation_method,label_id,region,distance_ERBB2
15,bfdoenpl-1,419.881133,401.067578,608,0,0,0,0,89,697,224.832977,103.769066,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,16,cell_boundaries,0.111969
21,bfdoompa-1,402.729277,424.485547,670,0,0,0,0,42,712,264.344697,52.832814,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,22,cell_boundaries,0.113438
22,bfdoopdk-1,409.032012,442.100781,640,0,0,0,0,98,738,216.569383,125.805317,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,23,cell_boundaries,0.201145
23,bfdpabnk-1,415.342070,419.055859,521,0,0,0,0,102,623,232.645008,106.162348,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,24,cell_boundaries,0.018618
27,bfdpidpb-1,422.116484,290.511426,498,0,0,0,0,88,586,168.071569,90.493128,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,28,cell_boundaries,1.101689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1628,nfnmmjmp-1,399.427031,286.350293,798,0,0,0,0,58,856,332.214543,71.753284,1,Segmented by interior stain (18S),1629,cell_boundaries,0.478545
1629,nfnmnkml-1,401.713164,245.970410,228,0,0,0,0,31,259,105.846254,31.744845,1,Segmented by interior stain (18S),1630,cell_boundaries,2.102540
1634,nfnnbngg-1,449.851836,241.707227,299,0,0,0,0,47,346,108.826566,65.747502,1,Segmented by interior stain (18S),1635,cell_boundaries,2.663631
1636,nfnnffgc-1,446.790313,255.877148,591,0,0,0,0,76,667,228.129383,99.027660,1,Segmented by interior stain (18S),1637,cell_boundaries,1.187785
1641,nfnnkbag-1,442.173613,233.756543,242,0,0,0,0,50,292,80.107190,51.478127,1,Segmented by interior stain (18S),1642,cell_boundaries,3.727364

In [71]:
st.ps.distance_to_membrane("ERBB2")

/home/lazic/.local/share/uv/python/cpython-3.12.11-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

,cell_id,distance_to_outline_ERBB2,cell_area,distance_to_outline_inverse_ERBB2
0,bfdoenpl-1,2.961290,224.832977,0.581112
1,bfdoompa-1,4.195833,264.344697,0.488192
2,bfdoopdk-1,1.838809,216.569383,0.737448
3,bfdpabnk-1,0.954741,232.645008,1.023428
4,bfdpidpb-1,2.747561,168.071569,0.603290
...,...,...,...,...
193,nfnmmjmp-1,2.830414,332.214543,0.594395
194,nfnmnkml-1,0.559947,105.846254,1.336370
195,nfnnbngg-1,0.472821,108.826566,1.454292
196,nfnnffgc-1,0.669686,228.129383,1.221981
197,nfnnkbag-1,0.053660,80.107190,4.316937

In [72]:
sdata["table"].obs[
    sdata["table"].obs["distance_to_outline_ERBB2"].notna()
    | sdata["table"].obs["distance_to_outline_inverse_ERBB2"].notna()
]

,cell_id,x_centroid,y_centroid,transcript_counts,control_probe_counts,genomic_control_counts,control_codeword_counts,unassigned_codeword_counts,deprecated_codeword_counts,total_counts,cell_area,nucleus_area,nucleus_count,segmentation_method,label_id,region,distance_ERBB2,distance_to_outline_ERBB2,distance_to_outline_inverse_ERBB2
15,bfdoenpl-1,419.881133,401.067578,608,0,0,0,0,89,697,224.832977,103.769066,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,16,cell_boundaries,0.111969,2.961290,0.581112
21,bfdoompa-1,402.729277,424.485547,670,0,0,0,0,42,712,264.344697,52.832814,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,22,cell_boundaries,0.113438,4.195833,0.488192
22,bfdoopdk-1,409.032012,442.100781,640,0,0,0,0,98,738,216.569383,125.805317,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,23,cell_boundaries,0.201145,1.838809,0.737448
23,bfdpabnk-1,415.342070,419.055859,521,0,0,0,0,102,623,232.645008,106.162348,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,24,cell_boundaries,0.018618,0.954741,1.023428
27,bfdpidpb-1,422.116484,290.511426,498,0,0,0,0,88,586,168.071569,90.493128,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,28,cell_boundaries,1.101689,2.747561,0.603290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1628,nfnmmjmp-1,399.427031,286.350293,798,0,0,0,0,58,856,332.214543,71.753284,1,Segmented by interior stain (18S),1629,cell_boundaries,0.478545,2.830414,0.594395
1629,nfnmnkml-1,401.713164,245.970410,228,0,0,0,0,31,259,105.846254,31.744845,1,Segmented by interior stain (18S),1630,cell_boundaries,2.102540,0.559947,1.336370
1634,nfnnbngg-1,449.851836,241.707227,299,0,0,0,0,47,346,108.826566,65.747502,1,Segmented by interior stain (18S),1635,cell_boundaries,2.663631,0.472821,1.454292
1636,nfnnffgc-1,446.790313,255.877148,591,0,0,0,0,76,667,228.129383,99.027660,1,Segmented by interior stain (18S),1637,cell_boundaries,1.187785,0.669686,1.221981
1641,nfnnkbag-1,442.173613,233.756543,242,0,0,0,0,50,292,80.107190,51.478127,1,Segmented by interior stain (18S),1642,cell_boundaries,3.727364,0.053660,4.316937

#### Compute all in one run

In [82]:
# No merging into sdata

sdata = sd.read_zarr("/g/huber/users/lazic/src/SegTraQ/tests/data/xenium_sdata.zarr")

st = segtraq.SegTraQ(sdata, labels_to_cell_id_key="label_id")
st.run_point_statistics("ERBB2", inplace=False)

/tmp/ipykernel_424963/3628047196.py:3: UserWarning: SpatialData is not stored in the most current format. If you want to use Zarr v3, please write the store to a new location using `sdata.write()`.
  sdata = sd.read_zarr("/g/huber/users/lazic/src/SegTraQ/tests/data/xenium_sdata.zarr")
no parent found for <ome_zarr.reader.Label object at 0x7ffe242e6390>: None
no parent found for <ome_zarr.reader.Label object at 0x7ffe24184e00>: None

{'centroid_mean_coord_diff_ERBB2': 0      0.111969
 1      0.113438
 2      0.201145
 3      0.018618
 4      1.101689
          ...
 193    0.478545
 194    2.102540
 195    2.663631
 196    1.187785
 197    3.727364
 Name: distance_ERBB2, Length: 198, dtype: float64,
 'distance_to_membrane_ERBB2': 0      2.961290
 1      4.195833
 2      1.838809
 3      0.954741
 4      2.747561
          ...
 193    2.830414
 194    0.559947
 195    0.472821
 196    0.669686
 197    0.053660
 Name: distance_to_outline_ERBB2, Length: 198, dtype: float64,
 'distance_to_outline_inverse_ERBB2': 0      0.581112
 1      0.488192
 2      0.737448
 3      1.023428
 4      0.603290
          ...
 193    0.594395
 194    1.336370
 195    1.454292
 196    1.221981
 197    4.316937
 Name: distance_to_outline_inverse_ERBB2, Length: 198, dtype: float64}

In [ ]:
# Merging into sdata
sdata = sd.read_zarr("/g/huber/users/lazic/src/SegTraQ/tests/data/xenium_sdata.zarr")

st = segtraq.SegTraQ(sdata, labels_to_cell_id_key="label_id")
st.run_point_statistics("ERBB2", inplace=True)

/tmp/ipykernel_424963/3658728746.py:1: UserWarning: SpatialData is not stored in the most current format. If you want to use Zarr v3, please write the store to a new location using `sdata.write()`.
  sdata = sd.read_zarr("/g/huber/users/lazic/src/SegTraQ/tests/data/xenium_sdata.zarr")
no parent found for <ome_zarr.reader.Label object at 0x7ffe2432bfb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7ffe0ee7ae70>: None
/home/lazic/.local/share/uv/python/cpython-3.12.11-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)
/home/lazic/.local/share/uv/python/cpython-3.12.11-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [81]:
sdata["table"].obs[
    sdata["table"].obs["distance_to_outline_ERBB2"].notna()
    | sdata["table"].obs["distance_to_outline_inverse_ERBB2"].notna()
]

,cell_id,x_centroid,y_centroid,transcript_counts,control_probe_counts,genomic_control_counts,control_codeword_counts,unassigned_codeword_counts,deprecated_codeword_counts,total_counts,cell_area,nucleus_area,nucleus_count,segmentation_method,label_id,region,distance_ERBB2,distance_to_outline_ERBB2,distance_to_outline_inverse_ERBB2
15,bfdoenpl-1,419.881133,401.067578,608,0,0,0,0,89,697,224.832977,103.769066,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,16,cell_boundaries,0.111969,2.961290,0.581112
21,bfdoompa-1,402.729277,424.485547,670,0,0,0,0,42,712,264.344697,52.832814,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,22,cell_boundaries,0.113438,4.195833,0.488192
22,bfdoopdk-1,409.032012,442.100781,640,0,0,0,0,98,738,216.569383,125.805317,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,23,cell_boundaries,0.201145,1.838809,0.737448
23,bfdpabnk-1,415.342070,419.055859,521,0,0,0,0,102,623,232.645008,106.162348,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,24,cell_boundaries,0.018618,0.954741,1.023428
27,bfdpidpb-1,422.116484,290.511426,498,0,0,0,0,88,586,168.071569,90.493128,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,28,cell_boundaries,1.101689,2.747561,0.603290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1628,nfnmmjmp-1,399.427031,286.350293,798,0,0,0,0,58,856,332.214543,71.753284,1,Segmented by interior stain (18S),1629,cell_boundaries,0.478545,2.830414,0.594395
1629,nfnmnkml-1,401.713164,245.970410,228,0,0,0,0,31,259,105.846254,31.744845,1,Segmented by interior stain (18S),1630,cell_boundaries,2.102540,0.559947,1.336370
1634,nfnnbngg-1,449.851836,241.707227,299,0,0,0,0,47,346,108.826566,65.747502,1,Segmented by interior stain (18S),1635,cell_boundaries,2.663631,0.472821,1.454292
1636,nfnnffgc-1,446.790313,255.877148,591,0,0,0,0,76,667,228.129383,99.027660,1,Segmented by interior stain (18S),1637,cell_boundaries,1.187785,0.669686,1.221981
1641,nfnnkbag-1,442.173613,233.756543,242,0,0,0,0,50,292,80.107190,51.478127,1,Segmented by interior stain (18S),1642,cell_boundaries,3.727364,0.053660,4.316937